<?php
$labels['mh_title'] = '邮件高亮';
$labels['mh_matches'] = '匹配';
$labels['mh_color'] = '颜色';
$labels['mh_delete'] = '删除';
$labels['mh_delete_description'] = '删除这个规则';
$labels['mh_add'] = '增加规则';
$labels['mh_add_description'] = '在这行下方增加另外一个规则';
$labels['deleteconfirm'] = '您真的要删除这个规则吗?';
// these should never happen, but add anyways
$labels['headererror'] = '邮件规则中的错误';
$labels['inputempty'] = '一个或多个匹配规则是空的';
$labels['invalidcolor'] = '无效的颜色';
?>
